##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (testray.main.component.name == "Upgrades Lima") AND \
        (testray.component.names == "Friendly URL Service")

##
## Testray
##

    testray.main.component.name=Friendly URL Service
