dependencies {
	compileOnly group: "commons-digester", name: "commons-digester", version: "1.8.1"
	compileOnly group: "commons-validator", name: "commons-validator", version: "1.5.1"
}

deployDependencies {
	from configurations.compileOnly

	include "commons-digester-*.jar"
	include "commons-validator-*.jar"
}